加载或保存张量

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(12)
torch.save(x, 'x-file.pt')
x2 = torch.load('x-file.pt')
x2 == x

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

存储一个张量列表

In [2]:
y = torch.arange(4)
torch.save([x, y], 'xy-files.pt')
x2, y2 = torch.load('xy-files.pt')
(x2, y2)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([0, 1, 2, 3]))

写入或读取从字符串映射到张量的字典

In [3]:
dict = {'x': x, 'y': y}
torch.save(dict, 'xy-dict.pt')
dict2 = torch.load('xy-dict.pt')
dict2

{'x': tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 'y': tensor([0, 1, 2, 3])}

加载或保存模型参数

In [24]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, X):
        return self.output(self.linear(X))
net = MLP()
X = torch.rand((2, 20))
Y = net(X)

In [ ]:
torch.save(net.state_dict(), 'mlp-params.pt') # state_dict()函数返回参数有序字典 

In [ ]:
clone = MLP() # 先创建一个实例
clone.load_state_dict(torch.load('mlp-params.pt')) # 加载state_dict后再写入覆盖load_state_dict()
clone.eval() # 切评估模式 会影响Dropout层和BatchNorm层 使得每次评估都一致 但对F.dropout需要另传training = False关闭

MLP(
  (linear): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [27]:
Y == clone(X)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])